name: Publish cht-deploy to npm

env:
  PACKAGE_PATH: ./scripts/deploy

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/deploy/**'
      - '!scripts/deploy/tests/**'
      - '!scripts/deploy/README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.PACKAGE_PATH }}

      - name: Check if version exists
        id: version-check
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          PACKAGE_NAME=$(jq -r '.name' package.json)
          if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" version 2>/dev/null; then
            echo "Version $PACKAGE_VERSION already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version $PACKAGE_VERSION is new"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ env.PACKAGE_PATH }}

      - name: Publish to npm
        if: steps.version-check.outputs.exists == 'false'
        run: npm publish
        working-directory: ${{ env.PACKAGE_PATH }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
